### ISSUE TITLE
Lab 8--Test Cases

### ISSUE THREAD

**Issue by Kenludiaz** [URI-CSC/212-fall-2020#1]
Hello,
For Lab 8 Test Case 2, Denmark will be in the map since the data file contains entries for both Greenland, Denmark and just Denmark.
`
    if (inMap(cases, "Denmark")){
        std::cout << "Test Case 2: Failed" << std::endl;
        std::cout << "A country that should not be in the map was inserted." << std::endl;
        return 1;
    }
`
View lines 177 & 178 of the data file:
"
,,Greenland,Denmark,2020-10-27 04:24:45,71.7069,-42.6043,17,0,16,1,"Greenland, Denmark",29.944338758542944,0.0
,,,Denmark,2020-10-27 04:24:45,56.2639,9.5018,41412,708,32237,8467,Denmark,714.9611296427282,1.7096493769921761
"
This test case is therefore incorrect.

**Comment by cesteves** [comment]
Good catch! While the dataset was updated since last Fall, I neglected to double-check the test cases. 

An update was pushed out ~5m after you had posted this. The new test cases are updated.
